DROP INDEX IF EXISTS idx_outbox_events_pending_created_at;
DROP INDEX IF EXISTS idx_outbox_events_topic_key_unique;
DROP TABLE IF EXISTS outbox_events;
DROP INDEX IF EXISTS idx_avatars_status;
DROP INDEX IF EXISTS idx_avatars_user_id_active;
DROP INDEX IF EXISTS idx_avatars_user_id_created_at;
DROP TABLE IF EXISTS avatars;
DROP INDEX IF EXISTS idx_users_email_active_unique;
DROP TABLE IF EXISTS users;
