image:
  repository: gophprofile
  tag: local
  pullPolicy: Never

config:
  appEnv: local
  kafka:
    brokers: gophprofile-kafka:9092
    consumerGroup: gophprofile-avatar-worker
  s3:
    endpoint: http://gophprofile-minio:9000
    bucket: gophprofile-avatars
    usePathStyle: true
    region: us-east-1

secret:
  values:
    databaseUrl: postgres://gophprofile:gophprofile@gophprofile-postgres:5432/gophprofile?sslmode=disable
    s3AccessKey: minioadmin
    s3SecretKey: minioadmin

server:
  replicaCount: 1

worker:
  replicaCount: 1

migrations:
  enabled: true

serviceMonitor:
  enabled: true
  labels:
    release: kube-prometheus-stack

prometheusRule:
  enabled: true
  labels:
    release: kube-prometheus-stack
