{{- if and .Values.secret.create (not .Values.secret.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "gophprofile.secretName" . }}
  labels:
    {{- include "gophprofile.labels" . | nindent 4 }}
type: Opaque
stringData:
  DATABASE_URL: {{ .Values.secret.values.databaseUrl | quote }}
  S3_ACCESS_KEY: {{ .Values.secret.values.s3AccessKey | quote }}
  S3_SECRET_KEY: {{ .Values.secret.values.s3SecretKey | quote }}
  VAULT_TOKEN: {{ .Values.secret.values.vaultToken | quote }}
{{- end }}
