global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: gophprofile-server
    metrics_path: /metrics
    static_configs:
      - targets:
          - server:9090

  - job_name: gophprofile-worker
    metrics_path: /metrics
    static_configs:
      - targets:
          - worker:9091
